<!-- Pricing Section -->
<section id="pricing" class="py-24 bg-white">
    <div class="container mx-auto px-6">
        <div class="text-center mb-20">
            <h2 class="text-5xl font-bold text-gray-900 mb-6" data-en="Flexible Plans for All" data-ar="خطط مرنة للجميع">Flexible Plans for All</h2>
            <p class="text-2xl text-gray-600 max-w-5xl mx-auto leading-relaxed" data-en="Flexible pricing plans designed to match the size of your company and your specific needs — whether you're just starting out or already managing a growing business." data-ar="خطط أسعار مرنة مصممة لتناسب حجم شركتك واحتياجاتك المحددة - سواء كنت قد بدأت للتو أو تدير بالفعل عملاً متنامياً.">
                Flexible pricing plans designed to match the size of your company and your specific needs — whether you're just starting out or already managing a growing business.
            </p>
        </div>
        
        <!-- Pricing Toggle -->
        <div class="flex justify-center items-center mb-16">
            <div class="bg-gray-100 rounded-2xl p-2 flex">
                <button class="px-8 py-3 rounded-xl bg-white shadow-lg text-gray-900 font-semibold transition-all duration-300" id="monthly-btn" data-en="Monthly" data-ar="شهري">Monthly</button>
                <button class="px-8 py-3 rounded-xl text-gray-600 font-semibold transition-all duration-300" id="yearly-btn" data-en="Yearly" data-ar="سنوي">Yearly</button>
            </div>
            <div class="ml-6 bg-green-100 text-green-800 px-4 py-2 rounded-full text-sm font-semibold" data-en="Save 20%" data-ar="وفر 20%">
                Save 20%
            </div>
        </div>
        
        <!-- Pricing Cards Container -->
        <div class="flex justify-center">
            <div class="grid md:grid-cols-3 gap-8 max-w-6xl" id="pricing-cards-root">
                <!-- Pricing cards will be dynamically generated by JavaScript -->
            </div>
        </div>
        
        <!-- Custom Package Information Section -->
        <div class="mt-20 bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-gray-800 dark:to-gray-900 rounded-3xl p-12 border-2 border-blue-200 dark:border-gray-600">
            <div class="text-center mb-12">
                <h3 class="text-4xl font-bold text-gray-900 dark:text-white mb-6" data-en="Custom Package - Choose What You Need" data-ar="الباقة المخصصة - اختر ما تحتاجه">Custom Package - Choose What You Need</h3>
                <p class="text-xl text-gray-700 dark:text-gray-300 max-w-4xl mx-auto leading-relaxed" data-en="Tell us about your company's specific needs and we'll create a custom solution that fits perfectly." data-ar="أخبرنا عن احتياجات شركتك المحددة وسنقوم بإنشاء حل مخصص يناسبك تماماً.">
                    Tell us about your company's specific needs and we'll create a custom solution that fits perfectly.
                </p>
            </div>
            
            <!-- Contact CTA -->
            <div class="text-center">
                <p class="text-lg text-gray-700 dark:text-gray-300 mb-8" data-en="Ready to create your custom solution? Contact us now!" data-ar="مستعد لإنشاء حلولك المخصصة؟ اتصل بنا الآن!">Ready to create your custom solution? Contact us now!</p>
                <div class="flex flex-col sm:flex-row gap-4 justify-center">
                    <a href="#" class="inline-flex items-center bg-blue-600 text-white px-8 py-4 rounded-2xl hover:bg-blue-700 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 btn-hover-animate">
                        <i class="fas fa-phone mr-3 text-xl"></i>
                        <span class="font-semibold text-lg" data-en="Call Us Now" data-ar="اتصل بنا الآن">Call Us Now</span>
                    </a>
                    <a href="#" class="inline-flex items-center bg-green-600 text-white px-8 py-4 rounded-2xl hover:bg-green-700 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 btn-hover-animate">
                        <i class="fab fa-whatsapp mr-3 text-xl"></i>
                        <span class="font-semibold text-lg" data-en="WhatsApp" data-ar="واتساب">WhatsApp</span>
                    </a>
                    <a href="#" class="inline-flex items-center bg-indigo-600 text-white px-8 py-4 rounded-2xl hover:bg-indigo-700 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 btn-hover-animate">
                        <i class="fas fa-envelope mr-3 text-xl"></i>
                        <span class="font-semibold text-lg" data-en="Email Us" data-ar="راسلنا">Email Us</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
